### ISSUE TITLE
Remove restrictions to Rasperry Pi in docs.

### ISSUE THREAD

**Issue by leifnel** [fchanson/node-red-contrib-arp#1]
The node works perfectly fine on standard debian, probably on other linux variants.
No need to limit it to pi's in the docs.

**Comment by fchanson** [comment]
@leifnel Thanks for your comment.
I just updated the package.

**Comment by leifnel** [comment]
About on github still say

This node provides the content of the ARP table, ONLY on Raspberry Pi
